spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  profiles:
    active: local
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 3
        initial-interval: 1000

server:
  port: 8443
  ssl:
    enabled: true
    client-auth: need
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    trust-store: ${SSL_TRUSTSTORE_PATH}
    trust-store-password: ${SSL_TRUSTSTORE_PASSWORD}
    trust-store-type: PKCS12

jwks:
  url: ${JWKS_URL:https://as.localdev.codaline/.well-known/jwks.json}
  cache-ttl: ${JWKS_CACHE_TTL:5m}