spring:
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}

  cloud:
    gateway:
      routes:
        - id: accounts-route
          uri: http://accounts-service:8081
          predicates:
            - Path=/open-banking/accounts/v2/**
          filters:
            - AddResponseHeader=X-Gateway-Version, 1.0.0
            - name: FapiMtlsValidation
            - name: JtiReplay
            - name: ConsentValidation
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${gateway.rate-limit.replenish-rate}
                redis-rate-limiter.burstCapacity: ${gateway.rate-limit.burst-capacity}
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@consentKeyResolver}"

jwt:
  issuer: https://as.localdev.codaline
  audience: https://gateway.localdev.codaline

gateway:
  rate-limit:
    replenish-rate: 10
    burst-capacity: 20

logging:
  level:
    br.com.codaline: INFO