server:
  port: 8080

gateway:
  rate-limit:
    replenish-rate: 10
    burst-capacity: 20

jwks:
  url: https://as.localdev.codaline/.well-known/jwks.json
  cache-ttl: 5m

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  cloud:
    gateway:
      httpserver:
        wiretap: false
      httpclient:
        wiretap: false
      routes:
        - id: accounts-route
          uri: http://localhost:8081
          predicates:
            - Path=/open-banking/accounts/v2/**
          filters:
            - AddResponseHeader=X-Gateway-Version, 1.0.0
            - name: FapiMtlsValidation
            - name: JtiReplay
            - name: ConsentValidation
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${gateway.rate-limit.replenish-rate}
                redis-rate-limiter.burstCapacity: ${gateway.rate-limit.burst-capacity}
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@consentKeyResolver}"